### ISSUE TITLE
Technical View name

### ISSUE THREAD

**Issue by MartinStenzig** [SAP-samples/teched2021-ANA160#6]
The documentation specifies to use the technical name 'E_mobility-Teched'. DWC complains and automatically updates it to 'E_mobilityTeched'. Nothing dramatic, but I figured I let you know.

**Comment by boefbrak** [comment]
> The documentation specifies to use the technical name 'E_mobility-Teched'. DWC complains and automatically updates it to 'E_mobilityTeched'. Nothing dramatic, but I figured I let you know.

Thanks so noted.
